name: Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag'
        required: true
        type: string
      release:
        description: 'Release'
        required: true
        type: boolean
        default: false

jobs:
  build:
    name: Build
    permissions:
      id-token: write
      contents: write
      attestations: write
    uses: ./.github/workflows/make.yml
    with:
      tag_name: ${{ inputs.tag_name }}
      release: ${{ inputs.release }}
